# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20170530_0944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='Tag',
        ),
        migrations.RenameModel(
            old_name='ActivityType',
            new_name='TagType',
        ),
    ]
