# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20170530_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tags',
        ),
        migrations.DeleteModel(
            name='TagType',
        ),
    ]
